### ISSUE TITLE
Wizard navigation button location is inconsistent

### ISSUE THREAD

**Issue by rhuss** [redhat-ipaas/ipaas-ui#218]
For connections the navigation buttons are on top, for integrations they are at the button. See screenshots.

![screen shot 2017-03-08 at 12 46 23](https://cloud.githubusercontent.com/assets/99080/23702826/45d3cd2a-03fd-11e7-8d39-49a9bba75dfd.png)

![screen shot 2017-03-08 at 12 46 09](https://cloud.githubusercontent.com/assets/99080/23702829/49978dfc-03fd-11e7-93fb-477ec2857506.png)

**Comment by kahboom** [comment]
Thanks @rhuss ! We had discussed with the UXD team that buttons were being moved to the top when possible, however, looking at [this](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/222155516_Fom_Template) design they may have forgotten to add the 'Next' buttons, unless it's supposed to automatically take you to the next view [here](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/222155518_Name_Integration) on select (I don't think that's the case). I'll ask them now.

**Comment by sjcox-rh** [comment]
@kahboom and @rhuss, for certain pages where the user has to make a selection in order to continue, we agreed there was no need for a next button since selection would automatically take you to the next view like you mentioned above. Since that's the case, the user would never have to click on the next button, and that may be confusing if we leave it on the page for these cases.

Let me know if you have any concerns about this! would be happy to discuss further :]

**Comment by kahboom** [comment]
Thanks for the clarification @sjcox-rh ! :)

**Comment by rhuss** [comment]
My intention in fact was that the location on top for connection and at the bottom for integration is inconsistent.  Now that the wizard buttons are on the top for integrations, I'm fine ;-)

**Comment by kahboom** [comment]
Ty @rhuss !
