### ISSUE TITLE
Integration name input field easy to overlook

### ISSUE THREAD

**Issue by rhuss** [redhat-ipaas/ipaas-ui#239]
The input text field for the integration name (i.e. when creating an integration) is separate from other text input fields. It's on the top over step flow which can be super easily overlooked (as it happens several times for @jimmidyson and me while working on the demo). I suggest to put in proximity to the other text fields.

Also, the "Save" button must not be enabled when no name has been entered as the name is mandatory.

**Comment by kahboom** [comment]
I completely agree with you and thought about this for quite a bit.. the design looks a bit more intuitive because the placeholder text is black, but even then I think this could be improved with maybe a walk-thru or something similar:

This is the design:

![from scratch](https://cloud.githubusercontent.com/assets/3844502/23794527/86db27b6-055e-11e7-9067-b37e60d9a8e4.png)



And here is what we currently have:

<img width="1440" alt="screenshot 2017-03-10 06 54 08" src="https://cloud.githubusercontent.com/assets/3844502/23794519/7d733060-055e-11e7-927e-62fd66fc8098.png">

Regarding the "Save" button, I believe it was re-enabled for development purposes, but @gashcrumb  can probably speak to this.

Thanks for the feedback! I'll probably create a separate GH issue for the "Save" button just so that it doesn't get overlooked.

**Comment by gashcrumb** [comment]
So the first screen when you go to create an integration should be this which should sort this usability issue, this just hasn't made it in yet.

![screencapture-redhat-invisionapp-share-jg9jwfd5h-1489512332648](https://cloud.githubusercontent.com/assets/351660/23913553/bbcb1770-08b9-11e7-8f1f-8049dd4adc7d.png)

**Comment by gashcrumb** [comment]
The name/description page needs to go in on this sprint.  Also as discussed with UXD the current input field needs to become a link along with the pencil icon which will take the user back to this name/description page.
