### ISSUE TITLE
Create Integration: Improve Save or Add Step Page

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#241]
This is a "rest stop" for the user to decide whether they want to add a step in the integration or save/publish the integration. The sidebar shows the actions that they can take, but what can we do with the main content area that is not duplicated? For the first step, it makes sense, but after they add a step or connection then what should be shown to the user?

![save or add step](https://cloud.githubusercontent.com/assets/3844502/24177112/a75bfd28-0e76-11e7-848d-11876f58dc7a.jpg)

**UPDATE**: This "rest stop" should only be shown for the first step or connection that users are adding for this integration. An expanded tooltip with a list of options to either add a connection or a step will be shown to the user upon clicking the [ + ] plus icon in the progress line.

**Comment by TovaCohen** [comment]
Is it okay if I ask questions here? Let me know if not.
If I understand more, maybe I can suggest what the user needs to see.
Can you tell me what a step is?
Is it the citizen user that is deciding whether to add a step?
Does the citizen user get a bunch of steps to choose from?
Does an admin user set up for the steps that a citizen user chooses from?
What does it mean to publish an integration?

**Comment by kahboom** [comment]
@TovaCohen - Despite the fact that we discussed pushing technical writing for after RH summit, feel free to ask questions on here or to create GH issues, just be aware of the fact that we may take a while (possibly after Summit depending on the nature of the question) to respond! :) It's always good to have it in writing so we don't forget in the future when we come back to re-assess.

Note to self: We've received new designs for this view and I'll be updating the issue description with them shortly.

**Comment by TovaCohen** [comment]
On the "Add to Integration" page, for the first time it appears, can you include text such as the following? I am assuming that there is a way substitute the actual connector names where I said "Twitter" and "Salesforce".  I am not sure the connection names are needed here. I think the connector names would be clearer to the citizen user. But I am not certain.   Also, some of my text is probably wrong, but I hope you get the idea of the kind of content that I think belongs here.  Why would a user choose another connection rather than a step? Can you give me an example of when this is the right thing to do?

Hope this helps:

Add to Integration

After the Twitter connection sends data, there can be a step or another connection that operates on the data before it reaches the Salesforce connection. 

If you do not need to operate on the data between the start and end connections, click Save. This makes your integration available for activation. 

Otherwise, you can choose one of the following steps:

   Data Mapper lets you map input fields to output fields.

   Filter lets you use simple scripting to pass along only the data of interest.

   Log sends messages to the integrations log file. 

Or, add an additional connection when you want to ...  ????

To add a step or connection, click the plus icon in the left pane or click a button below.

**Comment by TovaCohen** [comment]
Sorry!

**Comment by TovaCohen** [comment]
Also, whenever you are listing options, alphabetical order is usually the most helpful to the user.
Pick a style for when to use capitalization and apply it consistently. For example, I see a lowercase i here:
Dashboard > Create an integration
But the rest of the titles and the button labels use an initial cap for Integration, for example, Add to Integration, Add an Integration, Add a Step.  I know this is trivial. But consistency speeds the user. Honest!

**Comment by kahboom** [comment]
@TovaCohen - Thanks for the feedback. For things we can draw out I'd say to create separate GH issues or they'll get lost in conversation. I fixed the Create an Integration not being properly capitalized in a recent PR. I didn't even remember you had commented on that, but it drove me crazy lol. If you notice any other areas where that happens, I'd create a GH issue and label it as `Support & Docs`. Thanks again! :) 👍
