### ISSUE TITLE
Integration -> Create -> Connection flow start not active

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-ui#295]
this is actually first catch of e2e tests :)
![after_1584](https://cloud.githubusercontent.com/assets/8707241/24208401/d3ae768c-0f23-11e7-9b2f-4d61d1b87dad.png)

test report [here](https://htmlpreview.github.io/?https://gist.githubusercontent.com/jludvice/0a95b5a7bd01ad2035ee1128d828fab5/raw/7fb449cca51e82286aef367a87ee8d71cc44f306/integration-start-inactive.html)

**Comment by kahboom** [comment]
Thank you @jludvice ! That's awesome. For my own personal reference, the narrative test that failed was for `And she is prompted to select a "Start" connection from a list of available connections`.
@jludvice What are you testing for exactly? It should be the `active` class on the parent menu. If so, I believe that should be fixed as of this morning. The sidebar is highlighted because that is the step that she is on. If it's something else, let me know and I'll update the code to reflect that.

**Comment by jludvice** [comment]
I'm glad we have same failures ;)
![fail](https://cloud.githubusercontent.com/assets/8707241/24212684/706324f8-0f30-11e7-9b10-959aebad3579.png)

Which parent menu do you mean?
I was checking if there is `round active` class on the round circle of flow start
![active-class](https://cloud.githubusercontent.com/assets/8707241/24212937/2c9ff8b2-0f31-11e7-88c3-1f095aae7bb9.png)

The test was passing when I developed it.

**Comment by kahboom** [comment]
@jludvice When I checked, it was showing `inactive` no matter what, so I thought it was a bug that randomly came about.. so I made it so that the parent menu item, in this case "Set up this Connection" (highlighted in blue) would use the class `current` if it's active. Having said that, the `active` class for the round icon should still be correct, so I'll check that now and fix it if it's not working properly.

**Comment by jludvice** [comment]
Good morning @kahboom. 
It looks like this one is resolved by #316 right?

**Comment by kahboom** [comment]
Yep, that's correct @jludvice . Closing now. 👍
