### ISSUE TITLE
Dashboard: Empty State

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#300]
## Overview
Need to update the Dashboard page so that it shows the proper empty state when no integrations have been created. Should have minimal logic. Entails the following:
- Add HTML & SCSS to reflect designs & incorporate logic.
- Add respective methods in component to display Connections at the bottom, as shown in the design (Connections replaced Templates for now).

### Designs

![dashboard v7-empty](https://cloud.githubusercontent.com/assets/3844502/24213480/f9b62bd8-0f08-11e7-8de9-fb86d34c1251.png)

## Reference
- [GitHub: Dashboard](https://github.com/redhat-ipaas/ipaas-ui/issues/296)
- [GitHub: API Issue](https://github.com/redhat-ipaas/ipaas-rest/issues/246)
- [InVision: Design](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/210743184_Dashboard_V7-Empty)
- [JIRA Issue: UI](https://issues.jboss.org/browse/IPAAS-281)
- [JIRA User Story](https://issues.jboss.org/browse/IPAAS-279)

**Comment by TovaCohen** [comment]
When the expert user creates a connection, is it always considered to be a connection template?
When you create a template, are you always creating a connection template? In other words, is that the only kind of template?
I am wondering if the citizen user is always selecting from a set of connection templates rather than a set of connections. 
On the Connection Templates, what are the Dev and Update boxes for?

**Comment by kahboom** [comment]
Whoops
