### ISSUE TITLE
Show progress while creating an integration

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-ui#373]
When creating integration and click on `Publish` there is no feedback on progress.
One may click `Publish` infinitelly times.
Could we disable `Publish` button after click and disable some progress animation?
I think this animation (or picutre) **would be great place to inform user what cool stuff we're doing behind the scenes**.

Sth like, _hold on, we're creating project in your github account, it will take just one minute_ ?
![screenshot_20170403_162623](https://cloud.githubusercontent.com/assets/8707241/24614094/7b8d2d48-188a-11e7-823b-486691d38c84.png)

**Comment by kahboom** [comment]
@jludvice I agree that we shouldn't leave the user in limbo while the integration is being created, especially since it takes so long, however, there are a few different ways we can approach this problem. Looping in @sjcox-rh and @dongniwang for advice (and possibly designs if necessary?).

- **Progress bar.** In my experience, progress bars tend to be a bit of a lie and it can be difficult to make them look realistic. It's often more a pain than it's worth even though they can look very nice.
- **Integration status.** We can do the same we were planning to do for the state of an integration on the Integration List page (see #303 and possibly #302).
- **Loading state.** We could show a loading state (dim screen, loading cursor, etc) and a toast notification stating that the integration is being created, to please wait, this may take a few seconds, etc. before the user is redirected back to the Integration List page.

And whatever other ideas you guys have. :)

**Comment by dongniwang** [comment]
I think the most important thing here is how long does it take to create/publish a project? Do we have an estimated time frame on that? 

- If it's within a minute or so, I think we can keep users on the same page and display a loading state. 
- If it's going to take more than a minute, we should probably display a modal window letting users know that it's going to take a longer time to create/publish the project and they will be brought to the integration list page. Then we return users to the integration list and utilize toast notification for the project statues. 

cc: @sjcox-rh - what do you think?

**Comment by KurtStam** [comment]
From what I've seen it's around 15 seconds or so. But it depends on the workload and availability of things like GitHub and OpenShift. If things fail, we will write a message into the integration (statusMessage) and try again periodically (every minute). So let's say if you're github creds are wrong (or GitHub is offline) then it should say in that message. You have then time to fix them, and it will retry. So it can take very much longer in situations like these. The UI can subscribe to update events on the integration to show updates to the statusMessage and currentStatus.

**Comment by gashcrumb** [comment]
it'd be nice if the call to actually create the integration was decoupled from all the backend stuff like creating the repo etc. so that 'saving' an integration was always a quick operation.  Perhaps we need a new status like 'Creating' that the UI can use to reflect that status.  Having a quick save operation would also be kinda crucial if we ever want to support background saves, like whenever the user makes a change, as that was the original design, but due to the slowness of the save operation, we're currently stuck with a save button...

**Comment by jimmidyson** [comment]
Yeah that is what we aim the rest API to do, simply validate and save to storage. The async controller skid then handle the required source updates and openshift resource management.

**Comment by gashcrumb** [comment]
Yeah, so then if we get that, then this really becomes a non-issue though we can't really start auto-saving until we have a name I guess...

**Comment by kahboom** [comment]
Had a meeting with @dongniwang @sjcox-rh @gashcrumb @jimmidyson a moment ago -- this will be resolved once we have a global toast notification system in place and update the Integration List to look like the most recent designs, which reflect their statuses.

After creating an integration the user should:

- Immediately get a toast notification that lets them know their integration is being created and activated.
- Get redirected to the Integration List, where they will see their newly created integration, likely in an "In Progress" state where (for now) they won't be able to edit or delete it, possibly not even be able to view the detail page for it.
- Once the integration has been created and activated, they should receive a toast notification at the top right hand corner notifying them of this - even if they have navigated to another area of the application (hence the idea of a _global_ notification system).

Closing this issue as we have others open for this. I might create a new one for redirecting the user to the Integration List view sooner, but that may not be necessary with the toast notification.
