### ISSUE TITLE
Error dialog appears to late

### ISSUE THREAD

**Issue by rhuss** [redhat-ipaas/ipaas-ui#434]
When publishing an integration and when this fails (e.g. because of https://github.com/redhat-ipaas/ipaas-rest/issues/272), then I don't get any error dialog but the screen remains the same.

The error appears. in the Javascript console and Network tab, though.

When I know press "Publish" a **second** time, then error dialog (from the former try) appears immediately _and_ a second publish is triggered (which of course also fails).

I would expect the error dialog to show up immediately when the http error response arrives.

**Comment by kahboom** [comment]
@gashcrumb - I was going to ask toast notifications here, should probably hold off until this is fixed right?

**Comment by rhuss** [comment]
its not only when pushing the button that then the dialog appears, it happens on any even (e.g. when focussing on an input field, then the dialog appears.

**Comment by gashcrumb** [comment]
yeah, the issue here is a change detection issue, there's something screwy with angular's change detection on some of these views that I've been noticing but haven't been able to narrow down what's causing it.

I wouldn't use a toast notification for the error message though, we currently use the dialog as I'm still not convinced we'll always get back a consistent JSON response yet.  Also, part of the reason we stay on the page currently is when you go out of the integration editor we don't store the current integration locally.  So if we just jump back to the integration list *before* the request to save the integration completes, we risk losing the user's current work.

Again, the save HTTP operation still takes much longer than it's supposed to.
