### ISSUE TITLE
Alignment of Cards in Dashboard

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-ipaas/ipaas-ui#472]
I can't tell for sure, but it looks like the top of the cards might not be aligned in the dashboard:

![unnamed](https://cloud.githubusercontent.com/assets/16257540/25165664/745ab4a6-248c-11e7-9d25-fb423f63b99e.png)

**Comment by gashcrumb** [comment]
So it lines up looks like according to this screen ruler.  I'm guess it's an optical illusion caused by the additional contrast, if I look at that area enough my eyes really bug out :-)

<img width="740" alt="capture" src="https://cloud.githubusercontent.com/assets/351660/25182757/a621851c-24e3-11e7-955e-1f42d6142514.PNG">

**Comment by kahboom** [comment]
It looks aligned to me as well, but we can always add a border if anything. Locally it may not look as nice as it would in the demo.
